spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank_cards
    username: postgres
    password: admin

  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

  application:
    name: bank-cards
